added mkat -nt, -to, t options (tag support) added ability to catalog arbitrary path to mkat added burn -m option (passthrough options to mkat) updated manual pages

diff --git a/mkat b/mkat
--- a/mkat
+++ b/mkat
@@ -27,25 +27,48 @@ RCFILE=mkatrc
 function usage {
   echo "usage: $0 [option]";
   echo "  -f			overwrite list file"
+  echo "  -t <tag[,tag]...>     write list file with 'tags:' string"
   echo "  -s <regex>		search the CD database"
+  echo "  -nt			don't search tags with -s (no tags)"
+  echo "  -to <tag[,tag]...>	search within tags only (tags only)"
   echo "  -m <file>...		make md5 sum(s) and search for them in the db"
   echo "      --md5dir <dir>	print files with md5 sums not present in the db"
+  echo "  -p <path>		catalog path instead of a CD"
   echo "  -y			cycle { mkat; eject; }"
   echo "  -q			be quiet"
   echo "  -h, --help		print this help"
   exit $1
 }
 
+function check_option {
+  name=$1; val=$2
+  if [ -z "$val" ]; then
+    echo >&2 "$name option requires argument"
+    usage 1
+  fi
+}
+
 #process parameters
 found=1
 while [ $found ]; do
   case "$1" in
+    "-f") FORCE_OVERWRITE=1 ;;
     "-h"|"--help") usage 0 ;;
     "-q") CHILD_PARAMS="-q"; GREP_PARAMS="-q" ;;
     "-y") CYCLE_CATALOG=1 ;;
+    "-p") CATALOG_PATH=$2
+          CATALOG_PATH=${CATALOG_PATH%%/}
+          check_option $*; shift ;;
     "--md5dir")
       DIR="$2"
       [ -z "$DIR" ] && DIR=. ;;
+    "-s") REGEX="$2"; check_option $*; shift ;;
+    "-nt") FILTER_TAGS=1 ;;
+    "-to") TAG_REGEX="$2"; TAG_REGEX="(${TAG_REGEX//,/|/})"
+	   check_option $*; shift ;;
+    "-t")
+      TAGS="$2"; TAGS=${TAGS//,/ }
+      check_option $*; shift ;;
     *) unset found ;;
   esac
   [ $found ] && shift
@@ -63,11 +86,27 @@ if [ "$DIR" ]; then
   exit
 fi
 
+#tag search (-to)
+if [ "$TAG_REGEX" ]; then
+  grep $GREP_PARAMS -i -E "^tags:.+$TAG_REGEX" "$LISTDIR"/*.list
+  exit $?
+fi
+
 #search the database with grep (-s option)
-[ _$1 = _"-s" ] && { grep $GREP_PARAMS -i -E "$2" "$LISTDIR"/*.list; exit $?; }
+if [ "$REGEX" ]; then
+  IFS=''
+  res=`grep $GREP_PARAMS -i -E "$REGEX" "$LISTDIR"/*.list`
+  if [ $? -eq 0 ]; then
+    if [ $FILTER_TAGS ]; then
+      echo $res | grep -v -E "(^|:)tags:"; exit $?
+    else
+      echo $res; exit 0
+    fi
+  fi
+fi
 
 #search by md5 sum of a file
-if [ _"$1" = _"-m" ]; then
+if [ "_$1" = "_-m" ]; then
   shift
   md5sum "$@" | awk '{ printf "%s|", $1 }' | sed 's/|$/\n/' | xargs $MKAT -s
   exit $?
@@ -83,23 +122,38 @@ if [ $CYCLE_CATALOG ]; then
 fi
 
 #catalog the CD
-LABEL=`isoinfo -d -i $DRIVE | sed -ne 's/Volume id: //p'`
-[ -z "$LABEL" ] && { echo "could not obtain CD label"; LABEL="NO_LABEL"; }
-DEST="$LISTDIR/$LABEL.list"
-{ [ _$1 != _"-f" ] \
+if [ -z "$CATALOG_PATH" ]; then
+  LABEL=`isoinfo -d -i $DRIVE | sed -ne 's/Volume id: //p'`
+  [ -z "$LABEL" ] && { echo "could not obtain CD label"; LABEL="NO_LABEL"; }
+else
+  LABEL="$CATALOG_PATH"
+fi
+
+if [ "$CATALOG_PATH" ]; then
+  FNAME=${CATALOG_PATH#/}
+  FNAME=${FNAME//\//.}
+  CD=$CATALOG_PATH
+  TAGS="$TAGS filesystem"; TAGS=${TAGS# }
+else
+  FNAME=$LABEL
+  TAGS="$TAGS cd"; TAGS=${TAGS# }
+fi
+DEST="$LISTDIR/$FNAME.list"
+{ [ -z $FORCE_OVERWRITE ] \
   && [ -e "$DEST" ] ; } && \
   { echo >&2 "file already exists: '$DEST'"; exit 1; }
 
 {
 echo $LABEL
+[ "$TAGS" ] && echo "tags: $TAGS"
 IFS='
 '
 for f in `find $CD -mindepth 1`; do
-  rel=`echo "$f" | sed -ne "s!$CD!!;s!^/!!p"`
-  if [ -d "$f" ]; then
-    echo $rel
-  elif [ -f "$f" ]; then
+  rel=`echo "$f" | sed -ne "s!${CD%%/}/!!p"`
+  if [ -f "$f" ]; then
     echo -e $rel:`du -h "$f" | awk '{print $1}'`:`md5sum "$f" | awk '{ print $1}'`
+  else
+    echo $rel
   fi
 done
 } | tee "$DEST"
